### ISSUE TITLE
Add responsive and desktop modal 

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#163]
Create a simple modal system, supporting markdown to display the details of a data layer when clicking on the "a propos du calque" button)

This component should be seperate from the industrie-popover component, so it can be used for about/layer modales but also when clicking on a POI on the map

- Markdown parser
- Text should be scrollable on desktop and mobile
- Waiting for desktop design @SeongHunChandra

**Comment by lutangar** [comment]
Shall we transfer the markdown part of this issue to [__Datatlas__](https://github.com/datatlas-erasme/datatlas/issues) ?
