### ISSUE TITLE
 Integration of industries loading screen

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#180]
Add the following sections to the existing progress bar
- Img
	- Background color
	- Setup a loading bar with the following states
		- Loading instance data
		- Loading layers
		- Application of styles
		- BONUS Cosmetic : Display the number of data Ex Data structure : 10/300

![1-mobile-MIND-V3](https://user-images.githubusercontent.com/8368283/201979160-dfbe5609-4afa-4468-a254-f50604bfb701.png)

**Comment by lutangar** [comment]
> Superceded in __Datatlas__ by https://github.com/datatlas-erasme/datatlas/issues/247
