### ISSUE TITLE
Add a new component bottom bar / footer for desktop

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#181]
- [ ]  About text + icon
  - When issue #163  completed add button to call modal about
- [ ]  Ajouter Add text + icon
  - Waiting for design @SeongHunChandra 
- [ ] Add 3d view button 
  - Add option to display in 3d in conf file instance
- [ ]  Desktop version 
  - Waiting for design @SeongHunChandra 

![image (2)](https://user-images.githubusercontent.com/8368283/201982846-04edd8fa-9875-4069-ae44-2eb49fd6f2ee.jpg)

**Comment by lutangar** [comment]
> superceded in __Datatlas__ https://github.com/datatlas-erasme/datatlas/issues/50
