### ISSUE TITLE
Add mobile button "Recherche & filtres de données"

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#182]
- [ ]  On click open about panel and open poi
- [ ]  Keep in mind the possibility that later the burger icon and the "search and data filter" section will be two separate buttons

![image (1)](https://user-images.githubusercontent.com/8368283/201984145-a66fd9d9-3c1c-4881-938f-d3eaab1f495b.jpg)

![6-mobile-MIND-V3](https://user-images.githubusercontent.com/8368283/201984631-4900ccda-f8d1-4188-93c9-174b5106a8f8.png)

**Comment by lutangar** [comment]
> superceded by https://github.com/datatlas-erasme/datatlas/issues/50 and https://github.com/datatlas-erasme/datatlas/issues/172
