### ISSUE TITLE
Possibility to choose the theme typo in the instance conf file

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#184]
Being able to choose type in conf file for 
- H1,H2,H3
- p,a  etc ...

For ex : 
```json
{
"fonts" : ["titles" : "Roboto", "body": "Roboto"]
}
```

**Comment by lutangar** [comment]
Roboto will be the default typo in __Datatlas__  for user filters, see https://github.com/datatlas-erasme/datatlas/issues/50
