### ISSUE TITLE
Rewrite the crowdsourcing button

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#185]
When clicking on "Ajouter" opense a clickable section who redirects ot a form 

- [ ] Rewrite this component, maybe even renaming it ?

- [ ] Waiting for design @SeongHunChandra 

![image (2)](https://user-images.githubusercontent.com/8368283/201989699-4b693a11-5f79-4a73-aea0-1193f920b5eb.jpg)

**Comment by lutangar** [comment]
Will be done in https://github.com/datatlas-erasme/datatlas/issues/88
