### ISSUE TITLE
Improve docker build by caching layers

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/manger-local#95]
**Is your feature request related to a problem? Please describe.**
Docker build take more than 5 minutes

**Describe the solution you'd like**
Cache the node modules install if package.json has not been updated

**Ressource**
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

**Comment by Pipazoul** [comment]
`RUN npm install --legacy-peer-deps` is not cached

**Comment by Pipazoul** [comment]
Build time reduced to 1min (4 min before)

**Comment by aangelot** [comment]
@Pipazoul is this issue done ?
